---
  - name: Update system packages
    apt:
      update_cache: yes
      state: latest
      name:
        - ca-certificates
        - curl
        - git
        - gnupg
        - lsb-release
        - apt-transport-https
        - vim
        - jq

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository for Ubuntu 24.04 LTS
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu noble stable
      state: present

  - name: Update system packages
    apt:
      update_cache: yes
      state: latest
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - docker-buildx-plugin

  - name: Add user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Start docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Reset ssh connection
    meta: reset_connection